#!/bin/bash

PULPVERSION=0.2
XTRAPULPVERSION=0.3

rm lib/libpulp.a lib/libxtrapulp.a
rm include/pulp.h include/xtrapulp.h

cd pulp/$PULPVERSION/
make clean ; make -j
cd ../..

cd xtrapulp/$XTRAPULPVERSION/
make clean ; make -j
cd ../..

if [ ! -d include/ ]; then
  mkdir include
fi
if [ ! -d lib/ ]; then
  mkdir lib
fi

cp pulp/$PULPVERSION/libpulp.a lib/
cp pulp/$PULPVERSION/pulp.h include/
cp xtrapulp/$XTRAPULPVERSION/libxtrapulp.a lib/
cp xtrapulp/$XTRAPULPVERSION/xtrapulp.h include/
